# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RottenProfessors' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RottenProfessors

pod 'Firebase/Core'
pod 'FirebaseAuth'
pod 'FirebaseStorage'
pod 'SDWebImage'
pod 'MBProgressHUD'
pod 'SDWebImage'
pod 'FirebaseDatabase'

  target 'RottenProfessorsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RottenProfessorsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
